version: '3.8'

services:
  backend:
    build: .
    container_name: raposowear_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    # Não adicionamos o MySQL aqui pois você já possui um host externo ativo